# Generated by Django 5.2.4 on 2025-07-16 12:45

import django.db.models.deletion
import file_service.models.file_operation
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOperation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('dedup', 'Dedup'), ('unique', 'Unique'), ('filter', 'Filter')], default='dedup', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to=file_service.models.file_operation.upload_to)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_service.uploadedfile')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
